language: scala
scala:
   - 2.11.7
jdk:
   - oraclejdk8

before_script:
  - npm install
  - npm install -g gulp
  - gulp build

script:
  - sbt -Dtest.config=test clean coverage test
  - sbt coverageReport
  - sbt codacyCoverage
