language: scala
scala:
   - 2.11.7
jdk:
   - oraclejdk8

before_script:
  - psql -c 'CREATE DATABASE playdb ENCODING UTF8 LC_COLLATE = en_US.UTF-8 LC_CTYPE = en_US.UTF-8' -U postgres
  - psql -U postgres -d playdb -a -f ./conf/travis/1.sql
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6.zip