language: scala
scala:
   - 2.11.7
jdk:
   - oraclejdk8

services:
   - postgresql

before_script:
  - psql -c "CREATE DATABASE playdb ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8'" -U postgres
  - psql -U postgres -d playdb -a -f ./conf/evolutions/default/1.sql

script:
  - sbt -Dtest.config=test clean coverage test
  - sbt coverageReport
  - sbt codacyCoverage
